spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Url
    username: root
    password: Lider77@

  cloud:
    config:

      enabled: false


  main:
    banner-mode: off

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  security:
    basic:
     enabled: false

